questions = {
    1: [
        "Do you think that I've ever been in love?", 
        "Do you think that I've ever had my heart broken?",
        "What was your first impression of me?",
        "What do you think I do for a living?",
        "What about me is the most strange/unfamiliar to you?",
        "What is the worst assumption someone has made about you?",
        "What do you think my name is?",
        "What does my style tell you about me?",
        "Do you think I was popular in school? Explain.",
        "On a scale of 1-10, how clean do you think my car is? 1 being cleanest, 10 a complete disaster. Explain.",
        "Do you think I've ever checked my ex's phone for evidence?",
        "Who do you think my celebrity crush is?",
        "What is my body language telling you right now?",
        "What does my phone wallpaper say about me?",
        "What's the first thing you noticed about me?",
        "Finish the sentence: Just by looking at you, I'd think ____.",
        "What about me intrigues you?",
        "What do you think I'm most likely to splurge on?",
        "Do I look kind? Explain."
    ],
    2: [
        "Wildcard! Share your most played song at the moment.",
        "What is your defining characteristic?",
        "What's your fathers name and one thing about him?",
        "How are you really?",
        "What is the last thing you lied to your mom about?",
        "What's the most pain you've ever been in that wasn't physical?",
        "What's the most unexplainable thing that's ever happened to you?",
        "What have the past few weeks taught you?",
        "Wildcard! Call someone you admire. Let them know why you appreciate them.",
        "What have I tolerated from people in the past that I no longer have space for?",
        "Something that brought a smile to my face this week was ____.",
        "What are you feeling a lot of lately?",
        "What do you need right now but aren't communicating?",
        "What are you currently working through that others don't see?",
        "What was your biggest turning point in your dating life?",
        "What are you overthinking right now?",
        "What did your last relationship teach you about yourself?"
        "What belief about yourself no longer serves you?",
        "Wildcard! Set an intention for this week. Stick to it.",
        "Who in your life can you be most vulnerable with?",
        "Which one of your parents personality traits do you want to keep/let go of?",
        "Think of someone you admire. Why did this person come to mind?",
        "Are you lying to yourself about anything?",
        "What's your favorite part of yourself that isn't physical?",
        "What's the hardest part of dating you?",
        "What do you need to forgive yourself for?",
        "What's the hardest lesson you've learned in love?",
        "When you're asked how are you, how often do you answer truthfully?",
        "If MySpace were still a thing, what would my profile song be?",
        "Wildcard! Write a note to your younger selves.",
        "What is your most toxic trait you can admit to?",
        "What is your heart telling you?",
        "Who in your life deserve the biggest thank you? Let them know if you can.",
        "I feel loved when ____.",
        "Self love is ____.",
        "What can you be kinder towards yourself for today?",
        "What's your mothers name and the most valuable lesson she's taught you thus far?",
        "What are you still trying to prove to yourself?",
        "What have you been taking for granted lately?",
        "Is there a feeling you miss?",
        "Wildcard! Admit something.",
        "If you could have it your way, who would you be with? Where would you be? And what would you be doing?",
        "What do you need to hear right now?",
        "What about yourself is hard to admit?",
        "What's one thing you can do to be a better person?",
        "What question did this week/month/year leave you with?",
        "What lesson should you have learned by now?",
        "What dating advice would you give yourself?",
        "What title would you give this chapter in your life?",
        "When was the last time you felt most yourself?",
        "What part of your life works? What part of your life hurts?",
        "Wildcard! Press shuffle on your music library. Explain the first song that comes up.",
        "What been your happiest memory this past year?",
        "What would you never want to change about yourself?",
        "When was the last time you were able to use your pain to help someone else?",
        "Are you missing anyone right now? Do you think they are missing you too?",
        "What do you think my main love language is?",
        "What's the hardest truth you had to face this year?",
        "What's a feeling you're uncomfortable sharing with me?",
        "Wildcard! Recite or sing your favorite song lyrics that you can think of off the top of your head.",
        "What brought you the most unexpected joy recently?",
        "What was the lesson from your most recent painful experience?",
        "I know I'm in love when ____.",
        "Wildcard! Draw a picture.",
        "What about me is hardest for you to understand?",
        "Wildcard! What's your favorite memory we share?",
        "Have I ever challenged your worldview? How so?",
        "Have you changed your mind about anything recently?",
        "What's your favorite quote that you can think of off the top of your head?",
        "How did you get over your first love?",
        "What's the best lesson an ex has ever taught you?",
        "What do you need right now, more than anything?",
        "When was the last time you felt lucky to be you?",
        "When do you feel most optimistic?",
        "What has being single/in a relationship taught you about yourself, if anything?",
        "Do you think I fall in love easily? Why or why not?",
        "Wildcard! Make an assumption about me and explain it.",
        "Wildcard! Ask a question you'd be too afraid to ask, something that you wouldn't dare to ask."
    ],
    3: [
        "Is there anyone who's changed your life but doesn't know it?",
        "What do you think my strength is?",
        "When was the last time you surprised yourself?",
        "What would you like to learn from me?",
        "What can I teach you?",
        "What can we create together?",
        "Who do I remind you of?",
        "Based on what you've learned about me, do you have any show/movie recommendations?",
        "In a word, how would you describe our conversation?",
        "You hurt me but thank you for ____.",
        "Dear younger self: ____.",
        "Why do you think we met?",
        "What is something you learned about yourself this week?",
        "What would your younger self not believe about your life today?",
        "What is one thing you think I can do that would dramatically improve my life?",
        "How do our personalities compliment each other?",
        "Do you think the image you have of yourself matches the image people see you as?",
        "How can I add 1% more happiness to your life?",
        "What parts of yourself do you see in me?",
        "What question were you most afraid to answer?",
        "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
        "When this game is over, what will you remember about me?",
        "How would you describe me to a stranger?"
    ],
    4: [
        "Write a virtual message to your partner."
    ]
}